version: '3.8'
services:
  photo-ingestion-pipeline:
    container_name: photo-ingestion-pipeline
    build:
      context: ../
      dockerfile: docker/backend.Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ../data:/app/data
    restart: unless-stopped
